import {test,expect} from '@playwright/test';
import fs from 'node:fs';
const data=JSON.parse(fs.readFileSync(new URL('../../data/monitor.json',import.meta.url)));
for(const width of [320,390,860])test(`manufacturing and HBM progress at ${width}px`,async({page},testInfo)=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.setViewportSize({width,height:900});
  await page.route('**/data/monitor.json?*',r=>r.fulfill({json:data}));
  await page.goto('/#business');
  await page.locator('#manufacturing').waitFor({state:'visible'});
  await page.screenshot({path:testInfo.outputPath('company-page-top.png')});
  await page.goto('/#tech-sanand');
  await expect(page.locator('#tech-sanand')).toBeVisible();
  await expect(page.locator('#tech-sanand')).toContainText('封装测试');
  await expect(page.locator('#tech-sanand')).toContainText('颗/年');
  await page.locator('#tech-sanand .tech-evidence summary').click();
  await expect(page.locator('#tech-sanand .tech-evidence[open]')).toContainText('已实现年度封测量');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.locator('#tech-sanand').screenshot({path:testInfo.outputPath('sanand.png')});
  await page.goto('/#tech-dram_1gamma');
  await expect(page.locator('#tech-dram_1gamma')).toBeVisible();
  await page.goto('/#ecosystem');
  await expect(page.locator('#panel-ecosystem')).toBeVisible();
  await expect(page.locator('#panel-ecosystem')).not.toContainText('同类产品对照');
  await page.goto('/#product-comparison');
  await expect(page.locator('#cycle-supply #hbm-progress')).toBeVisible();
  const table=page.locator('#hbm-progress .hbm-table');
  await expect(table.locator('tbody tr')).toHaveCount(2);
  await expect(table.locator('thead')).toContainText('SK 海力士');
  await expect(table).not.toContainText('功耗');
  await page.locator('#hbm-progress').screenshot({path:testInfo.outputPath('hbm-progress.png')});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await table.locator('[data-tech-link="tech-skhynix_hbm4e"]').click();
  await expect(page.locator('#hbm-specs')).toHaveAttribute('open','');
  await expect(page.locator('#tech-skhynix_hbm4e')).toBeVisible();
  await page.locator('#tech-skhynix_hbm4e .tech-evidence summary').click();
  await expect(page.locator('#tech-skhynix_hbm4e .tech-evidence[open]')).toContainText('基准');
  await page.goto('/#business');
  await page.locator('#manufacturing [data-tech-link="tech-micron_hbm4"]').click();
  await expect(page.locator('#panel-industry')).toBeVisible();
  await expect(page.locator('#tech-micron_hbm4')).toBeVisible();
  await page.goto('/#tech-samsung_rdimm');
  await expect(page.locator('#panel-business #manufacturing')).toBeInViewport();
  await page.goto('/#tech-micron_rdimm256');
  await expect(page.locator('#panel-business #tech-micron_rdimm256')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
test('technology content survives the offline fallback',async({page},testInfo)=>{
  await page.route('**/data/*.json?*',r=>r.abort());
  await page.goto('/#tech-sanand');
  await expect(page.locator('#tech-sanand')).toBeVisible();
  await expect(page.locator('#freshness')).toContainText('备用资料');
});
